[package]
name = "aggregator"
version = "0.1.0"
edition = "2021"

[dependencies]
db               = { path = "../db" }
tokio            = { workspace = true }
fe2o3-amqp       = { workspace = true }
fe2o3-amqp-types = "0.8"
sqlx             = { workspace = true }
tracing          = { workspace = true }
tracing-subscriber = { workspace = true }
serde            = { workspace = true }
serde_json       = { workspace = true }
serde_yaml       = { workspace = true }
async-trait      = { workspace = true }
bytes            = "1"

[dev-dependencies]
mockall = { workspace = true }
tokio   = { workspace = true, features = ["test-util"] }
