"""UI backend server for the AI image generation pipeline.

FastAPI + WebSocket backend providing:

  REST endpoints
  ──────────────
  POST /session/start            — create a conversation
  POST /workflow/new             — create a workflow and first run within a conversation
  POST /workflow/{id}/resume     — resume a paused workflow (new run_id)
  POST /workflow/{id}/start-run  — enqueue a generation request for a workflow's current run
  POST /feedback                 — record thumbs up / down for an image
  GET  /history                  — list conversations, their workflows, and recent images
  GET  /image/{uuid}             — proxy ComfyUI image by UUID

  WebSocket endpoints
  ───────────────────
  WS /ws/gallery                 — push new image + decision events to the browser
  WS /ws/chat                    — bidirectional streaming chat with the tactical LLM

The server subscribes to two Artemis topics via STOMP:
  /topic/loop.events             — image generated by ComfyUI (captures image_path)
  /topic/tactical.decisions      — LLM decision per image (verdict + decision)

Image paths are cached in-process from loop.events messages and served via
/image/{uuid} by proxying to the ComfyUI URL.
"""

from __future__ import annotations

import asyncio
import json
import os
import re
import socket
import subprocess
import sys
import uuid as _uuid_mod
from pathlib import Path
from typing import Any
from urllib.parse import urlparse

import httpx
import stomp
from fastapi import FastAPI, WebSocket, WebSocketDisconnect
from fastapi.responses import FileResponse, Response
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel

sys.path.insert(0, str(Path(__file__).parent.parent.parent))
from config import load as _load_config  # noqa: E402

_cfg = _load_config()
_tac = _cfg.tactical
_model_cfg = _tac.get("model", {})

_COORDINATOR_SOCK: str = _cfg.database["path"] + ".sock"

# ── Chat backend configuration ────────────────────────────────────────────────
# The chat backend is configurable so the UI can be switched from the tactical
# LLM server to a strategic LLM server when that becomes available, without
# code changes. Set ui.chat_backend.server_url and ui.chat_backend.model_name
# in config.yaml to override. Falls back to the tactical LLM server.
_ui_cfg = _cfg.get("ui") or {}
_chat_backend_cfg = _ui_cfg.get("chat_backend") or {}
_LLM_SERVER_URL: str = (
    _chat_backend_cfg.get("server_url")
    or _model_cfg.get("server_url", "http://localhost:8080/v1")
)
_LLM_MODEL_NAME: str = (
    _chat_backend_cfg.get("model_name")
    or _model_cfg.get("model_name", "default")
)

_u = urlparse(_cfg.broker["stomp_url"])
_STOMP_HOST: str = _u.hostname or "localhost"
_STOMP_PORT: int = _u.port or 61613
_STOMP_USER: str = _u.username or ""
_STOMP_PASS: str = _u.password or ""

app = FastAPI(title="AI Image Pipeline UI")

# ── Static files ──────────────────────────────────────────────────────────────

_STATIC = Path(__file__).parent / "static"
app.mount("/static", StaticFiles(directory=str(_STATIC)), name="static")


@app.get("/")
async def root() -> FileResponse:
    """Serve the single-page UI."""
    return FileResponse(str(_STATIC / "index.html"))


# ── In-process image path cache ───────────────────────────────────────────────
# Populated from /topic/loop.events (image_uuid → ComfyUI URL or local path)

_image_paths: dict[str, str] = {}

# ── In-process credential store ────────────────────────────────────────────────
# Keyed by conversation_id. Never written to disk or the coordinator DB.
# Cleared when the server process exits or the conversation is explicitly ended.

_session_credentials: dict[str, dict[str, str]] = {}

# Regex to detect the structured download-trigger block the LLM emits.
_DOWNLOAD_RE = re.compile(
    r"<DOWNLOAD_MODELS>(.*?)</DOWNLOAD_MODELS>",
    re.DOTALL,
)


# ── Coordinator socket ────────────────────────────────────────────────────────


def _coordinator_call(req: dict) -> dict:
    """Send a JSON request to the coordinator Unix socket and return the response."""
    sock = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
    try:
        sock.connect(_COORDINATOR_SOCK)
        sock.sendall((json.dumps(req) + "\n").encode())
        buf = b""
        while b"\n" not in buf:
            chunk = sock.recv(65536)
            if not chunk:
                break
            buf += chunk
        return json.loads(buf.split(b"\n")[0])
    finally:
        sock.close()


# ── Gallery WebSocket manager ──────────────────────────────────────────────────


class _GalleryManager:
    """Manages broadcast to all connected gallery WebSocket clients."""

    def __init__(self) -> None:
        self._clients: set[WebSocket] = set()
        self._lock = asyncio.Lock()

    async def connect(self, ws: WebSocket) -> None:
        await ws.accept()
        async with self._lock:
            self._clients.add(ws)

    async def disconnect(self, ws: WebSocket) -> None:
        async with self._lock:
            self._clients.discard(ws)

    async def broadcast(self, data: Any) -> None:
        text = json.dumps(data)
        async with self._lock:
            dead: list[WebSocket] = []
            for client in self._clients:
                try:
                    await client.send_text(text)
                except Exception:
                    dead.append(client)
            for d in dead:
                self._clients.discard(d)


_gallery = _GalleryManager()


# ── STOMP listener (runs in a background thread) ───────────────────────────────


class _PipelineListener(stomp.ConnectionListener):
    """STOMP listener for loop.events (image ready) and tactical.decisions (verdict)."""

    def __init__(self, loop: asyncio.AbstractEventLoop) -> None:
        self._loop = loop

    def on_error(self, frame: stomp.utils.Frame) -> None:
        print(f"[ui/stomp] error: {frame.body}", file=sys.stderr)

    def on_message(self, frame: stomp.utils.Frame) -> None:
        try:
            msg = json.loads(frame.body)
        except Exception:
            return

        dest = frame.headers.get("destination", "")

        if "loop.events" in dest:
            # Capture image_path for proxying, then notify gallery of new image.
            image_uuid = msg.get("image_uuid", "")
            image_path = msg.get("image_path", "")
            if image_uuid and image_path:
                _image_paths[image_uuid] = image_path
            asyncio.run_coroutine_threadsafe(
                _gallery.broadcast({
                    "type":           "image_ready",
                    "image_uuid":     image_uuid,
                    "workflow_id":    msg.get("workflow_id", ""),
                    "conversation_id": msg.get("conversation_id", ""),
                    "sequence_number": msg.get("sequence_number", 0),
                }),
                self._loop,
            )

        elif "tactical.decisions" in dest:
            # Decision from the LLM — updates verdict in the gallery.
            asyncio.run_coroutine_threadsafe(
                _gallery.broadcast({
                    "type":           "decision",
                    "image_uuid":     msg.get("image_uuid", ""),
                    "decision":       msg.get("decision", {}).get("decision", ""),
                    "reasoning":      msg.get("decision", {}).get("reasoning", ""),
                    "confidence":     msg.get("decision", {}).get("confidence"),
                    "verdict":        msg.get("verdict", {}).get("verdict", ""),
                    "workflow_id":    msg.get("verdict", {}).get("workflow_id", ""),
                    "conversation_id": msg.get("verdict", {}).get("conversation_id", ""),
                }),
                self._loop,
            )


_stomp_conn: stomp.Connection | None = None


def _start_stomp(loop: asyncio.AbstractEventLoop) -> None:
    global _stomp_conn
    _stomp_conn = stomp.Connection(host_and_ports=[(_STOMP_HOST, _STOMP_PORT)])
    _stomp_conn.set_listener("", _PipelineListener(loop))
    _stomp_conn.connect(_STOMP_USER, _STOMP_PASS, wait=True,
                        headers={"client-id": "ui-server"})
    # Topics — broadcast, no competing consumption.
    _stomp_conn.subscribe(destination="/topic/loop.events",        id="ui-events",    ack="auto")
    _stomp_conn.subscribe(destination="/topic/tactical.decisions", id="ui-decisions", ack="auto")


@app.on_event("startup")
async def _on_startup() -> None:
    loop = asyncio.get_running_loop()
    await loop.run_in_executor(None, _start_stomp, loop)


# ── REST models ───────────────────────────────────────────────────────────────


class SessionStartRequest(BaseModel):
    name: str | None = None


class WorkflowNewRequest(BaseModel):
    conversation_id: str
    name: str | None = None
    workflow_path: str
    description: str | None = None
    budget_policy: str = "fresh"
    max_retries: int = 3
    max_inpaints: int = 2


class WorkflowResumeRequest(BaseModel):
    budget_policy: str | None = None
    max_retries: int | None = None
    max_inpaints: int | None = None


class WorkflowStartRunRequest(BaseModel):
    prompt: str
    run_id: str
    conversation_id: str
    workflow_path: str
    workflow_params: dict | None = None


class FeedbackRequest(BaseModel):
    image_uuid: str
    workflow_id: str
    run_id: str
    rating: str  # 'up' | 'down'
    comment: str | None = None


# ── REST endpoints ────────────────────────────────────────────────────────────


@app.post("/session/start")
async def session_start(req: SessionStartRequest) -> dict:
    """Create a new conversation and return its conversation_id."""
    resp = _coordinator_call({"op": "ConversationCreate", "name": req.name})
    return resp


@app.post("/workflow/new")
async def workflow_new(req: WorkflowNewRequest) -> dict:
    """Create a new workflow and its first run, returning workflow_id + run_id."""
    create_resp = _coordinator_call({
        "op":              "WorkflowCreate",
        "conversation_id": req.conversation_id,
        "name":            req.name,
        "workflow_path":   req.workflow_path,
        "description":     req.description,
        "budget_policy":   req.budget_policy,
        "max_retries":     req.max_retries,
        "max_inpaints":    req.max_inpaints,
    })
    if not create_resp.get("ok"):
        return create_resp

    workflow_id = create_resp["workflow_id"]

    # Create the first run immediately so the client has a run_id to use.
    resume_resp = _coordinator_call({"op": "WorkflowResume", "workflow_id": workflow_id})
    if not resume_resp.get("ok"):
        return resume_resp

    return {
        "ok":              True,
        "workflow_id":     workflow_id,
        "run_id":          resume_resp.get("run_id"),
        "conversation_id": req.conversation_id,
        "workflow_path":   req.workflow_path,
    }


@app.post("/workflow/{workflow_id}/resume")
async def workflow_resume(workflow_id: str, req: WorkflowResumeRequest) -> dict:
    """Resume a paused workflow, creating a new run."""
    payload: dict = {"op": "WorkflowResume", "workflow_id": workflow_id}
    if req.budget_policy is not None:
        payload["budget_policy"] = req.budget_policy
    if req.max_retries is not None:
        payload["max_retries"] = req.max_retries
    if req.max_inpaints is not None:
        payload["max_inpaints"] = req.max_inpaints
    resp = _coordinator_call(payload)
    return resp


@app.post("/workflow/{workflow_id}/start-run")
async def workflow_start_run(workflow_id: str, req: WorkflowStartRunRequest) -> dict:
    """Enqueue a generation request for a workflow's current run via STOMP."""
    image_uuid = str(_uuid_mod.uuid4())

    request_msg = {
        "image_uuid":       image_uuid,
        "session_uuid":     req.run_id,
        "sequence_number":  0,
        "workflow_path":    req.workflow_path,
        "workflow_id":      workflow_id,
        "conversation_id":  req.conversation_id,
        "prompt":           req.prompt,
        "workflow_params":  req.workflow_params or {},
    }

    if _stomp_conn and _stomp_conn.is_connected():
        _stomp_conn.send(
            destination="/queue/loop.request",
            body=json.dumps(request_msg),
            headers={"persistent": "true"},
        )
        return {"ok": True, "image_uuid": image_uuid}
    return {"ok": False, "error": "STOMP not connected"}


@app.post("/feedback")
async def feedback(req: FeedbackRequest) -> dict:
    """Record user thumbs up/down for an image."""
    resp = _coordinator_call({
        "op":          "FeedbackAdd",
        "image_uuid":  req.image_uuid,
        "workflow_id": req.workflow_id,
        "run_id":      req.run_id,
        "rating":      req.rating,
        "comment":     req.comment,
    })
    return resp


@app.get("/history")
async def history(conversation_id: str = "", workflow_id: str = "", limit: int = 50) -> dict:
    """Return recent chat messages and feedback for a workflow."""
    resp = _coordinator_call({
        "op":              "ContextGet",
        "conversation_id": conversation_id,
        "workflow_id":     workflow_id,
        "limit":           limit,
    })
    return resp


@app.get("/image/{image_uuid}")
async def get_image(image_uuid: str) -> Response:
    """Proxy the ComfyUI image for a given image_uuid.

    image_path is cached in-process from /topic/loop.events messages.
    """
    image_path = _image_paths.get(image_uuid)
    if not image_path:
        return Response(status_code=404, content=b"image not found or not yet generated")

    if image_path.startswith("http"):
        async with httpx.AsyncClient(timeout=30.0) as client:
            r = await client.get(image_path)
        return Response(content=r.content,
                        media_type=r.headers.get("content-type", "image/png"))

    path = Path(image_path)
    if path.exists():
        return Response(content=path.read_bytes(), media_type="image/png")
    return Response(status_code=404, content=b"image file not found on disk")


# ── Model download helper ──────────────────────────────────────────────────────

_REPO_ROOT = Path(__file__).parent.parent.parent
_VENV_PYTHON = str(_REPO_ROOT / "venv" / "bin" / "python")
_DOWNLOAD_SCRIPT = str(_REPO_ROOT / "scripts" / "download_models.py")


async def _run_download(conversation_id: str) -> str:
    """Run scripts/download_models.py with credentials from the session store.

    Credentials are passed as environment variables to the subprocess and are
    never written to disk. Returns a short status message for the chat UI.
    """
    creds = _session_credentials.get(conversation_id, {})
    env = {**os.environ}
    if creds.get("hf_token"):
        env["HF_TOKEN"] = creds["hf_token"]
    if creds.get("civitai_token"):
        env["CIVITAI_TOKEN"] = creds["civitai_token"]

    loop = asyncio.get_running_loop()
    proc = await loop.run_in_executor(
        None,
        lambda: subprocess.run(
            [_VENV_PYTHON, _DOWNLOAD_SCRIPT],
            env=env,
            capture_output=True,
            text=True,
            timeout=1800,  # 30 min max
        ),
    )
    if proc.returncode == 0:
        # Trim to last 20 lines so the chat response isn't overwhelming.
        lines = (proc.stdout or "").strip().splitlines()
        tail = "\n".join(lines[-20:]) if lines else "(no output)"
        return f"Download complete.\n```\n{tail}\n```"
    else:
        err = (proc.stderr or proc.stdout or "unknown error").strip()[-1000:]
        return f"Download failed (exit {proc.returncode}):\n```\n{err}\n```"


# ── Gallery WebSocket ──────────────────────────────────────────────────────────


@app.websocket("/ws/gallery")
async def ws_gallery(ws: WebSocket) -> None:
    """Gallery push endpoint. Sends image_ready and decision events to browsers."""
    await _gallery.connect(ws)
    try:
        while True:
            await ws.receive_text()  # keep alive; browser sends pings
    except WebSocketDisconnect:
        pass
    finally:
        await _gallery.disconnect(ws)


# ── Chat WebSocket ─────────────────────────────────────────────────────────────


@app.websocket("/ws/chat")
async def ws_chat(ws: WebSocket) -> None:
    """Bidirectional streaming chat with the tactical LLM.

    Browser sends JSON: {"conversation_id": "...", "workflow_id": "...", "message": "..."}
    Server streams back: {"type": "chunk", "text": "..."} then {"type": "done"}.

    Each exchange is stored via the coordinator ChatAdd op.
    """
    await ws.accept()
    try:
        while True:
            raw = await ws.receive_text()
            try:
                msg = json.loads(raw)
            except json.JSONDecodeError:
                await ws.send_text(json.dumps({"type": "error", "text": "invalid JSON"}))
                continue

            conversation_id = msg.get("conversation_id", "")
            workflow_id = msg.get("workflow_id")
            user_text = msg.get("message", "").strip()
            if not user_text:
                continue

            # Persist user message.
            _coordinator_call({
                "op":              "ChatAdd",
                "conversation_id": conversation_id,
                "workflow_id":     workflow_id,
                "role":            "user",
                "content":         user_text,
            })

            # Fetch recent chat context.
            context_resp = _coordinator_call({
                "op":              "ContextGet",
                "conversation_id": conversation_id,
                "workflow_id":     workflow_id or "",
                "limit":           20,
            })
            chat_history = context_resp.get("chat", []) if context_resp.get("ok") else []

            # Build messages for the LLM (exclude the message we just saved — last entry).
            messages = [{"role": "system", "content": _CHAT_SYSTEM_PROMPT}]
            for entry in (chat_history[:-1] if chat_history else []):
                role = entry.get("role", "user")
                messages.append({"role": role, "content": entry.get("content", "")})
            messages.append({"role": "user", "content": user_text})

            # Stream from llama.cpp server.
            assistant_text = ""
            try:
                async with httpx.AsyncClient(
                    timeout=httpx.Timeout(connect=10.0, read=None, write=10.0, pool=10.0)
                ) as client:
                    async with client.stream(
                        "POST",
                        f"{_LLM_SERVER_URL}/chat/completions",
                        headers={"Authorization": "Bearer none"},
                        json={
                            "model":       _LLM_MODEL_NAME,
                            "messages":    messages,
                            "stream":      True,
                            "temperature": 0.7,
                            "max_tokens":  2048,
                        },
                    ) as resp:
                        async for line in resp.aiter_lines():
                            if not line.startswith("data: "):
                                continue
                            data_str = line[6:]
                            if data_str.strip() == "[DONE]":
                                break
                            try:
                                chunk = json.loads(data_str)
                                delta = chunk["choices"][0]["delta"].get("content", "")
                                if delta:
                                    assistant_text += delta
                                    await ws.send_text(
                                        json.dumps({"type": "chunk", "text": delta})
                                    )
                            except Exception:
                                continue
            except (httpx.ConnectError, httpx.ConnectTimeout) as exc:
                msg_text = (
                    f"⚠️ Cannot reach the LLM server at **{_LLM_SERVER_URL}**. "
                    "Run `./loop/llama_cpp.sh start` to start it."
                )
                await ws.send_text(json.dumps({"type": "chunk", "text": msg_text}))
                assistant_text = msg_text
            except Exception as exc:
                await ws.send_text(json.dumps({"type": "error", "text": str(exc)}))

            # Intercept credential / download trigger block before persisting.
            download_task: asyncio.Task | None = None
            match = _DOWNLOAD_RE.search(assistant_text)
            if match:
                try:
                    payload = json.loads(match.group(1))
                    creds: dict[str, str] = {}
                    if payload.get("hf_token"):
                        creds["hf_token"] = payload["hf_token"]
                    if payload.get("civitai_token"):
                        creds["civitai_token"] = payload["civitai_token"]
                    if creds:
                        _session_credentials[conversation_id] = creds
                except Exception:
                    pass
                # Strip the block from the visible/persisted text.
                assistant_text = _DOWNLOAD_RE.sub("", assistant_text).strip()
                download_task = asyncio.create_task(_run_download(conversation_id))

            await ws.send_text(json.dumps({"type": "done"}))

            if assistant_text:
                _coordinator_call({
                    "op":              "ChatAdd",
                    "conversation_id": conversation_id,
                    "workflow_id":     workflow_id,
                    "role":            "assistant",
                    "content":         assistant_text,
                })

            # After the LLM response is sent, await the download and push result.
            if download_task is not None:
                await ws.send_text(json.dumps({
                    "type": "chunk",
                    "text": "\n\n⏳ Downloading models — this may take a while…\n",
                }))
                download_result = await download_task
                await ws.send_text(json.dumps({"type": "chunk", "text": download_result}))
                await ws.send_text(json.dumps({"type": "done"}))

    except WebSocketDisconnect:
        pass


_CHAT_SYSTEM_PROMPT = """\
You are the creative director assistant for an autonomous AI image generation pipeline
supporting both SDXL and Flux generative models with optional LoRA augmentation.

You help the user refine their creative vision: discussing subjects, aesthetics, lighting,
composition, workflow parameters, LoRA selection, model choice, and how to guide the
pipeline toward the desired output.

The pipeline runs scorers (CLIP, artifact detection, VLM) and a tactical LLM that makes
accept/retry/inpaint decisions based on scorer results. You can advise on prompts, settings,
model selection, LoRA choices, and workflows likely to perform well.

The model is Soar-qwen-72b-abliterated — uncensored with no content restrictions. Assist with
any creative direction the user describes, including mature or explicit themes.

Keep responses focused and actionable.
"""


# ── Entry point ───────────────────────────────────────────────────────────────


if __name__ == "__main__":
    import uvicorn

    ui_cfg = _cfg.get("ui", default={}) or {}
    host = ui_cfg.get("host", "0.0.0.0")
    port = int(ui_cfg.get("port", 7860))
    uvicorn.run("server:app", host=host, port=port, reload=False)
