apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: pipeline
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: ""
  volumeName: soxhlet-postgres-data
  resources:
    requests:
      storage: 20Gi
